---
- apparmor-profiles:
    - '/usr/bin/onioncircuits'
  users:
    - 'amnesia'
  commands:
    GETINFO:
      - 'version'
      - 'circuit-status'
      - 'stream-status'
      - 'ns/id/[a-fA-F0-9]+'
      - 'ip-to-country/\d+\.\d+\.\d+\.\d+'
  confs:
    usemicrodescriptors:
    __owningcontrollerprocess:
  events:
    SIGNAL:
      suppress: true
    CONF_CHANGED:
      suppress: true
    STATUS_SERVER:
      suppress: true
    STREAM:
    CIRC:
